class SharedPrefKey {

  static const String SHARED_PREF_A_STAFF = 'SHARED_PREF_A_STAFF';
  static const String SHARED_PREF_A_STAFF_FIT_AND_FIRM = 'SHARED_PREF_A_STAFF_FIT_AND_FIRM';

  static const String FIT_AND_FIRM_TIME_DUTATION = 'SHARED_PREF_A_STAFF_FIT_AND_FIRM_TIME_DUTATION';
  static const String FIT_AND_FIRM_GOAL = 'SHARED_PREF_A_STAFF_FIT_AND_FIRM_GOAL';
  static const String FIT_AND_FIRM_ATTACHMENT = 'SHARED_PREF_A_STAFF_FIT_AND_FIRM_ATTACHMENT';
  static const String FIT_AND_FIRM_DETAIL = 'SHARED_PREF_A_STAFF_FIT_AND_FIRM_DETAIL';
  static const String FIT_AND_FIRM_SUM = 'SHARED_PREF_A_STAFF_FIT_AND_FIRM_SUM';

}

